[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
meepmeep = "3CZyEWmVeZ962D1cxKdRHdZi1gU64T25xvxkd3xQdsDe"

[programs.devnet]
meepmeep = "3CZyEWmVeZ962D1cxKdRHdZi1gU64T25xvxkd3xQdsDe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/ha.nguyen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
