[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
meepmeep = "AamArorzVAsGS3b8vTtzbQDj9vLgTu2cvTYofxuV5EEt"

[programs.devnet]
meepmeep = "AamArorzVAsGS3b8vTtzbQDj9vLgTu2cvTYofxuV5EEt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/ha.nguyen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
