import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

const alienFont = localFont({
  src: './fonts/Infinegarian.otf',
  variable: '--font-alien',
})

const seuratFont = localFont({
  src: './fonts/Seurat.ttf',
  variable: '--font-seurat',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${seuratFont.variable}  ${alienFont.variable}`}>{children}</body>
    </html>
  )
}
